### ISSUE TITLE
Update DatePicker

### ISSUE THREAD

**Issue by quawsed** [stiftungswo/better-dime#403]
Currently we use a DateTime object (single moment in time) to represent an entire day (DD-MM-YYYY). This leads to timezone errors. For example after choosing a date with the DatePicker for an offer and passing it as an argument to the offers_controller, when parsed the time will be 22:00 the day before. One has to manually add 2 hours to again to compensate for the timezone error, not a great solution.

**Comment by dacin21** [comment]
+1, it's very easy to forget the +2h somewhere which will lead to bugs.

For example, here we only add 2h to the ending but not the begging, which will end up setting the beginning to a date one day earlier than what was entered :^)
https://github.com/stiftungswo/better-dime/blob/cef70d27188b04613b62eeee7ec38d3495d91c71/apir/app/controllers/v2/invoices_controller.rb#L34

**Comment by dacin21** [comment]
For DatePicker, can't we just use `moment.utc(date)` instead of `moment(date)` to avoid the time zone issues of the latter?
In general, whenever the user enters just a date (without a time), we should parse it as UTC as the backend / db also uses UTC.

When the user enters a date+time, things get more tricky. Ideally, we would display things in local time while using UTC in all the date strings we pass around.
